---
production:
  access_key_id: <%= ENV['AWS_S3_KEY_ID'] || 'not-used-access_key_id' %>
  secret_access_key: <%= ENV['AWS_S3_SECRET_KEY'] || 'not-used-secret_access_key' %>
  pre_curation:
    bucket: <%= ENV['AWS_S3_PRE_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRE_CURATE_REGION'] || 'us-east-1' %>
  post_curation:
    bucket: <%= ENV['AWS_S3_POST_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_POST_CURATE_REGION'] || 'us-east-1' %>
  preservation:
    bucket: <%= ENV['AWS_S3_PRESERVATION_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRESERVATION_REGION'] || 'us-west-1' %>
  dspace:
    bucket: <%= ENV['AWS_S3_DSPACE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_DSPACE_REGION'] || 'us-east-1' %>
  embargo:
    bucket: <%= ENV['AWS_S3_EMBARGO_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_EMBARGO_REGION'] || 'us-east-1' %>
staging:
  access_key_id: <%= ENV['AWS_S3_KEY_ID'] || 'not-used-access_key_id' %>
  secret_access_key: <%= ENV['AWS_S3_SECRET_KEY'] || 'not-used-secret_access_key' %>
  pre_curation:
    bucket: <%= ENV['AWS_S3_PRE_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRE_CURATE_REGION'] || 'us-east-1' %>
  post_curation:
    bucket: <%= ENV['AWS_S3_POST_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_POST_CURATE_REGION'] || 'us-east-1' %>
  preservation:
    bucket: <%= ENV['AWS_S3_PRESERVATION_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRESERVATION_REGION'] || 'us-west-1' %>
  dspace:
    bucket: <%= ENV['AWS_S3_DSPACE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_DSPACE_REGION'] || 'us-east-1' %>
  embargo:
    bucket: <%= ENV['AWS_S3_EMBARGO_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_EMBARGO_REGION'] || 'us-east-1' %>
development:
  access_key_id: <%= ENV['AWS_S3_KEY_ID'] || 'not-used-access_key_id' %>
  secret_access_key: <%= ENV['AWS_S3_SECRET_KEY'] || 'not-used-secret_access_key' %>
  pre_curation:
    bucket: <%= ENV['AWS_S3_PRE_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRE_CURATE_REGION'] || 'us-east-1' %>
  post_curation:
    bucket: <%= ENV['AWS_S3_POST_CURATE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_POST_CURATE_REGION'] || 'us-east-1' %>
  preservation:
    bucket: <%= ENV['AWS_S3_PRESERVATION_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_PRESERVATION_REGION'] || 'us-west-1' %>
  dspace:
    bucket: <%= ENV['AWS_S3_DSPACE_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_DSPACE_REGION'] || 'us-east-1' %>
  embargo:
    bucket: <%= ENV['AWS_S3_EMBARGO_BUCKET'] || 'example-bucket' %>
    region: <%= ENV['AWS_S3_EMBARGO_REGION'] || 'us-east-1' %>
test:
  access_key_id: "not-used-access_key_id"
  secret_access_key: "not-used-secret_access_key"
  pre_curation:
    bucket: "example-bucket"
    region: "us-east-1"
  post_curation:
    bucket: "example-bucket-post"
    region: "us-east-1"
  preservation:
    bucket: "example-bucket-preservation"
    region: "us-west-1"
  dspace:
    bucket: "example-bucket-dspace"
    region: "us-east-1"
  embargo:
    bucket: "example-bucket-embargo"
    region: "us-east-1"
